# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: bieber-bot

provider:
    name: aws
    runtime: python3.6
    iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: 'arn:aws:sns:us-east-1:465039758259:Test'
    - Effect: Allow
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
      Resource:
        - 'arn:aws:ssm:us-east-1:465039758259:parameter/PA_TEAM_ID'
        - 'arn:aws:ssm:us-east-1:465039758259:parameter/PA_SLACK_BOT_TOKEN'
        - 'arn:aws:ssm:us-east-1:465039758259:parameter/PA_SLACK_VERIFICATION_TOKEN'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { 'Fn::GetAtt': ['DynamoDBUsersTable', 'Arn' ] }
    environment:
        BIEBERED_TABLE: ${self:custom.tableName}


functions:
    initial_response:
        handler: wsgi.handler
        events:
            - http: POST /bieber
    response_followup:
        handler: bieber_followup.lambda_func
        events:
            - sns: 'arn:aws:sns:us-east-1:465039758259:Test'


plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
    tableName: 'BieberedUsersTable-${self:provider.stage}'
    wsgi:
        app: bieber.app
        packRequirements: false
    pythonRequirements:
        dockerizePip: non-linux


resources:
    Resources:
        DynamoDBUsersTable:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    -
                        AttributeName: user_id
                        AttributeType: S
                KeySchema:
                    -
                        AttributeName: user_id
                        KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:custom.tableName}
